# Generated by Django 3.0.8 on 2020-07-05 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200705_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='website',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
