# Generated by Django 3.0.8 on 2020-07-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20200706_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='language',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='name',
            name='language',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='language',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='language',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
