# Generated by Django 3.0.8 on 2020-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='source',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='version',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='name',
            name='source',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='version',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='source',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='version',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='website',
            name='source',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='version',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
