# Generated by Django 3.0.8 on 2020-07-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_phonenumber_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='type',
            new_name='data_type',
        ),
        migrations.AddField(
            model_name='address',
            name='data_type',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='data_type',
            field=models.CharField(default='default', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='data_type',
            field=models.CharField(default='default', max_length=127),
            preserve_default=False,
        ),
    ]
