# Generated by Django 3.0.8 on 2020-07-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20200707_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='type',
        ),
    ]
