# Generated by Django 3.0.8 on 2020-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_auto_20200708_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
